### ISSUE TITLE
Test/fix default path for MTG Arena on MacOS

### ISSUE THREAD

**Issue by NateSackett** [Alex-Van-Buren/mtga_collection_manager#3]
https://github.com/Alex-Van-Buren/mtga_collection_manager/blob/bd1e12fae81ddcac3e07e2c85f63b52dea7ab255/getMtgaPath.js#L13-L16

**Comment by Nate-Sackett** [comment]
Looking for help testing out the default path to Player.log on MacOS. This issue is open to anyone using a Mac with MTG Arena installed.

Please test/fix the default path to the Player.log. You can test if it works using the inventoryFinder.js file; if a json is outputted, without an error being thrown, it should be working. (Be sure that "Detailed Logs" is enabled for use of inventoryFinder.)

**Comment by NateSackett** [comment]
Collection Manager was dropped and reimagined in V2 as a React App. getMtgaPath was not used in the new project, and testing the path to automatically get the player log is unnecessary. Issue closed because code is depreciated.
